# Generated by Django 4.2.9 on 2026-09-07 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BloodTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hemoglobin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Gemoglobin (g/L)",
                    ),
                ),
                (
                    "rbc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Eritrotsitlar (10^12/L)",
                    ),
                ),
                (
                    "wbc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Leykotsitlar (10^9/L)",
                    ),
                ),
                (
                    "platelets",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Trombotsilar (10^9/L)",
                    ),
                ),
                (
                    "glucose",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Glyukoza (mmol/L)",
                    ),
                ),
                (
                    "creatinine",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Kreatinin (µmol/L)",
                    ),
                ),
                (
                    "bilirubin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Bilirubin (µmol/L)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Izohlar")),
            ],
            options={
                "verbose_name": "Qon tahlili natijasi",
                "verbose_name_plural": "Qon tahlili natijalari",
            },
        ),
        migrations.CreateModel(
            name="LabTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("nse", "NSE (Neyron-spetsifik enolaza)"),
                            ("s100b", "S100B oqsili"),
                            ("gfap", "GFAP (Gliafibrillyar kislotali oqsil)"),
                            ("blood", "Qon tahlili"),
                            ("csf", "Miya-orqa suyuqligi tahlili"),
                            ("other", "Boshqa"),
                        ],
                        max_length=20,
                        verbose_name="Tahlil turi",
                    ),
                ),
                ("test_date", models.DateTimeField(verbose_name="Tahlil sanasi")),
                (
                    "sample_collected_date",
                    models.DateTimeField(verbose_name="Namuna olingan sana"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Tugallangan"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Izohlar")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan sana"
                    ),
                ),
            ],
            options={
                "verbose_name": "Laboratoriya tahlili",
                "verbose_name_plural": "Laboratoriya tahillari",
                "ordering": ["-test_date"],
            },
        ),
        migrations.CreateModel(
            name="NeuroProteinResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "protein_type",
                    models.CharField(
                        choices=[("nse", "NSE"), ("s100b", "S100B"), ("gfap", "GFAP")],
                        max_length=20,
                        verbose_name="Oqsil turi",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Qiymat"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Masalan: ng/ml, pg/ml",
                        max_length=20,
                        verbose_name="O'lchov birligi",
                    ),
                ),
                (
                    "reference_range_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Me'yoriy diapazon (min)",
                    ),
                ),
                (
                    "reference_range_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Me'yoriy diapazon (max)",
                    ),
                ),
                (
                    "is_abnormal",
                    models.BooleanField(
                        default=False, verbose_name="Me'yordan chetlashgan"
                    ),
                ),
                ("interpretation", models.TextField(blank=True, verbose_name="Talqin")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "lab_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neuro_protein_results",
                        to="laboratory.labtest",
                        verbose_name="Laboratoriya tahlili",
                    ),
                ),
            ],
            options={
                "verbose_name": "Neyro-oqsil natijasi",
                "verbose_name_plural": "Neyro-oqsil natijalari",
                "ordering": ["-created_at"],
            },
        ),
    ]
