# Generated by Django 4.2.9 on 2026-09-07 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("laboratory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="labtest",
            name="ordered_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordered_tests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Buyurtma bergan",
            ),
        ),
        migrations.AddField(
            model_name="labtest",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_tests",
                to="patients.patient",
                verbose_name="Bemor",
            ),
        ),
        migrations.AddField(
            model_name="labtest",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_tests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bajargan laborant",
            ),
        ),
        migrations.AddField(
            model_name="bloodtestresult",
            name="lab_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blood_test_results",
                to="laboratory.labtest",
                verbose_name="Laboratoriya tahlili",
            ),
        ),
    ]
