# Generated by Django 4.2.9 on 2026-09-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonitoringSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Boshlanish sanasi"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tugash sanasi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("notes", models.TextField(blank=True, verbose_name="Izohlar")),
            ],
            options={
                "verbose_name": "Monitoring sessiyasi",
                "verbose_name_plural": "Monitoring sessiyalari",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="NeurologicalAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Baholash sanasi"
                    ),
                ),
                (
                    "consciousness_level",
                    models.CharField(max_length=100, verbose_name="Ong darajasi"),
                ),
                (
                    "muscle_tone",
                    models.CharField(max_length=100, verbose_name="Mushak tonusi"),
                ),
                ("reflexes", models.TextField(verbose_name="Reflekslar")),
                (
                    "seizure_activity",
                    models.BooleanField(
                        default=False, verbose_name="Tutqanoq faolligi"
                    ),
                ),
                (
                    "seizure_description",
                    models.TextField(blank=True, verbose_name="Tutqanoq tavsifi"),
                ),
                (
                    "fontanelle_status",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fontanel holati"
                    ),
                ),
                (
                    "pupil_response",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Ko'z qorachiq reaktsiyasi",
                    ),
                ),
                (
                    "assessment_notes",
                    models.TextField(blank=True, verbose_name="Baholash izohlari"),
                ),
            ],
            options={
                "verbose_name": "Nevrologik baholash",
                "verbose_name_plural": "Nevrologik baholashlar",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="VitalSigns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vaqt"),
                ),
                (
                    "heart_rate",
                    models.IntegerField(
                        help_text="Minutiga urishlar soni",
                        verbose_name="Yurak urishi (bpm)",
                    ),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(
                        help_text="Minutiga nafas olishlar soni",
                        verbose_name="Nafas olish (rpm)",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Harorat (°C)"
                    ),
                ),
                (
                    "blood_pressure_systolic",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Qon bosimi (sistolik)"
                    ),
                ),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Qon bosimi (diastolik)"
                    ),
                ),
                (
                    "oxygen_saturation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Qon kislorod to'yinganligi (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vital signs",
                "verbose_name_plural": "Vital signs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
