# Generated by Django 4.2.9 on 2026-09-07 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("monitoring", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalsigns",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Qayd qilgan",
            ),
        ),
        migrations.AddField(
            model_name="vitalsigns",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vital_signs",
                to="monitoring.monitoringsession",
                verbose_name="Sessiya",
            ),
        ),
        migrations.AddField(
            model_name="neurologicalassessment",
            name="assessed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Baholagan shifokor",
            ),
        ),
        migrations.AddField(
            model_name="neurologicalassessment",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="neurological_assessments",
                to="monitoring.monitoringsession",
                verbose_name="Sessiya",
            ),
        ),
        migrations.AddField(
            model_name="monitoringsession",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Yaratgan foydalanuvchi",
            ),
        ),
        migrations.AddField(
            model_name="monitoringsession",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monitoring_sessions",
                to="patients.patient",
                verbose_name="Bemor",
            ),
        ),
    ]
