# Generated by Django 4.2.9 on 2026-09-07 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Sana")),
                ("description", models.TextField(verbose_name="Tavsif")),
            ],
            options={
                "verbose_name": "Tibbiy tarix",
                "verbose_name_plural": "Tibbiy tarix",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medical_record_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Tibbiy karta raqami"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ism")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Familiya"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "O'g'il"), ("F", "Qiz")],
                        max_length=1,
                        verbose_name="Jinsi",
                    ),
                ),
                (
                    "birth_date",
                    models.DateTimeField(verbose_name="Tug'ilgan sana va vaqt"),
                ),
                (
                    "gestational_age",
                    models.IntegerField(
                        help_text="Homiladorlik muddati haftalarda",
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(44),
                        ],
                        verbose_name="Gestatsion yoshi (hafta)",
                    ),
                ),
                (
                    "birth_weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Tug'ilish og'irligi (kg)",
                    ),
                ),
                (
                    "birth_length",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Tug'ilish bo'yi (cm)",
                    ),
                ),
                (
                    "head_circumference",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Bosh aylanasi (cm)",
                    ),
                ),
                (
                    "apgar_score_1min",
                    models.IntegerField(
                        help_text="Apgar ko'rsatkichi 1 daqiqada",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Apgar (1 daqiqa)",
                    ),
                ),
                (
                    "apgar_score_5min",
                    models.IntegerField(
                        help_text="Apgar ko'rsatkichi 5 daqiqada",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Apgar (5 daqiqa)",
                    ),
                ),
                (
                    "mother_name",
                    models.CharField(max_length=200, verbose_name="Ona FIO"),
                ),
                ("mother_age", models.IntegerField(verbose_name="Ona yoshi")),
                (
                    "mother_phone",
                    models.CharField(max_length=20, verbose_name="Ona telefoni"),
                ),
                ("diagnosis", models.TextField(blank=True, verbose_name="Tashxis")),
                (
                    "complications",
                    models.TextField(blank=True, verbose_name="Asoratlar"),
                ),
                (
                    "treatment_plan",
                    models.TextField(blank=True, verbose_name="Davolash rejasi"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "admission_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Qabul qilingan sana"
                    ),
                ),
                (
                    "discharge_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Chiqarilgan sana"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan sana"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bemor",
                "verbose_name_plural": "Bemorlar",
                "ordering": ["-created_at"],
            },
        ),
    ]
