# Generated by Django 4.2.9 on 2026-09-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Sarlavha")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("patient_summary", "Bemor xulosasi"),
                            ("neuroprotein_trend", "Neyro-oqsillar trendi"),
                            ("statistical", "Statistik hisobot"),
                            ("custom", "Maxsus hisobot"),
                        ],
                        max_length=30,
                        verbose_name="Hisobot turi",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                (
                    "date_from",
                    models.DateField(blank=True, null=True, verbose_name="Sanadan"),
                ),
                (
                    "date_to",
                    models.DateField(blank=True, null=True, verbose_name="Sanagacha"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/%Y/%m/",
                        verbose_name="Fayl",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("xlsx", "Excel")],
                        default="pdf",
                        max_length=10,
                        verbose_name="Fayl turi",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "is_generated",
                    models.BooleanField(default=False, verbose_name="Yaratilgan"),
                ),
            ],
            options={
                "verbose_name": "Hisobot",
                "verbose_name_plural": "Hisobotlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Sana")),
                (
                    "total_patients",
                    models.IntegerField(default=0, verbose_name="Jami bemorlar"),
                ),
                (
                    "active_patients",
                    models.IntegerField(default=0, verbose_name="Faol bemorlar"),
                ),
                (
                    "total_tests",
                    models.IntegerField(default=0, verbose_name="Jami tahlillar"),
                ),
                (
                    "abnormal_results",
                    models.IntegerField(
                        default=0, verbose_name="Me'yordan chetlashgan natijalar"
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistika",
                "verbose_name_plural": "Statistikalar",
                "ordering": ["-date"],
            },
        ),
    ]
