# Generated by Django 4.2.9 on 2026-09-07 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Yaratgan foydalanuvchi",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                help_text="Ma'lum bemor uchun hisobot",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patients.patient",
                verbose_name="Bemor",
            ),
        ),
    ]
